function params = DEFAULT_HYPERPARAMS(varargin)    
    params = struct(...
                    'MaxObjectiveEvaluations'   ,150    ,...
                    'ShowPlots'                 ,false  ,...
                    'MaxTime'                   ,Inf    ,...
                    'KFold'                     ,5      , ...
                    'UseParallel'               ,true   ,...
                    'Repartition'               ,true	); 
end
