function labels = fix_labels(labels)
    if iscategorical(labels)
        oldnames = categories(labels);
    else
        oldnames = labels;
    end
    
    if any(contains(oldnames,'\_'))
        pairs = {   'encoder', 'Running Speed';...
                    'EyeCam\_L\_forelimb', 'I. Forelimb MI' ; ...
                    'EyeCam\_R\_forelimb', 'C. Forelimb MI' ; ...
                    'BodyCam\_L\_whisker', 'I. Whisker MI' ; ...
                    'BodyCam\_R\_whisker', 'C. Whisk.Pad MI' ; ...
                    'EyeCam\_Perioral', 'Peri-oral MI' ; ...
                    'trigger', 'C. AirPuff' ; ...
                    'baseline', 'F0'};
    else
        pairs = {   'encoder', 'Running Speed';...
                    'EyeCam_L_forelimb', 'I. Forelimb MI' ; ...
                    'EyeCam_R_forelimb', 'C. Forelimb MI' ; ...
                    'BodyCam_L_whisker', 'I. Whisker MI' ; ...
                    'BodyCam_R_whisker', 'C. Whisk.Pad MI' ; ...
                    'EyeCam_Perioral', 'Peri-oral MI' ; ...
                    'trigger', 'C. AirPuff' ; ...
                    'baseline', 'F0'};
    end

    newnames = oldnames;
    for el = 1:numel(oldnames)
        if ~contains(oldnames{el}, 'shuffle')
            newnames{el} = pairs{find(~cellfun(@isempty, (strfind(pairs, oldnames{el})))), 2};
        end
    end

    if iscategorical(labels)
        labels          = renamecats(labels,oldnames,newnames);
    else
        labels          = newnames;
    end
end

